site_name: Sojiro's Blog
site_url: https://blog.sojiro.me
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  palette:
    primary: teal
    accent: teal
nav:
  - index.md
  - Blog:
    - blog/index.md
plugins:
  - blog:
      enabled: true
      blog_dir: blog
      blog_toc: false
      post_dir: "{blog}/posts"
      post_url_max_categories: 1
      post_slugify_separator: "-"
      post_excerpt_max_authors: 1
      post_excerpt_max_categories: 5
      post_excerpt_separator: <!-- more -->
      post_readtime: true
      post_readtime_words_per_minute: 265
      archive: true
      archive_name: Archive
      archive_pagination: true
      archive_pagination_per_page: 10
      archive_toc: false
      categories: true
      categories_name: Categories
      categories_slugify_separator: "-"
      categories_pagination: true
      categories_pagination_per_page: 10
      categories_toc: false
      authors: true
      authors_file: "{blog}/.authors.yml"
      authors_profiles: false
      authors_profiles_name: Authors
      authors_profiles_pagination: true
      authors_profiles_pagination_per_page: 10
      authors_profiles_toc: false
      pagination: true
      pagination_per_page: 10
      pagination_keep_content: false
      draft: false
      draft_on_serve: true
      draft_if_future_date: false
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/sojiro14
    - icon: fontawesome/brands/github
      link: https://github.com/sojiro14
  generator: false
copyright: Copyright &copy; 2014 - 2024 sojiro.me